Repository PNUMeat/comon-fe, pull requests merged in 2024-11, with the labels that each got.

#1 공통 컴포넌트 Flex, Container 추가
  src/components/commons/Container.tsx
  src/components/commons/Flex.tsx
Labels: 🎨 design

#3 이미지 관련 공통 컴포넌트 추가
  src/assets/Login/loginVector.png
  src/components/commons/GlassCard.tsx
  src/components/commons/LazyImage.tsx
  src/components/commons/Spacer.tsx
  src/pages/Login/Login.tsx
  src/pages/Login/LoginForm.tsx
  src/routes/path.ts
  src/routes/router.tsx
Labels: 🎨 design

#5 폰트 Pretendard 적용
  package-lock.json
  package.json
  src/api/Login.ts
  src/api/apiInstance.ts
  src/assets/fonts/Pretendard-Black.subset.woff2
  src/assets/fonts/Pretendard-Bold.subset.woff2
  src/assets/fonts/Pretendard-ExtraBold.subset.woff2
  src/assets/fonts/Pretendard-ExtraLight.subset.woff2
  src/assets/fonts/Pretendard-Light.subset.woff2
  src/assets/fonts/Pretendard-Medium.subset.woff2
  src/assets/fonts/Pretendard-Regular.subset.woff2
  src/assets/fonts/Pretendard-SemiBold.subset.woff2
  src/assets/fonts/Pretendard-Thin.subset.woff2
  src/components/commons/Header.tsx
  src/main.css
  src/pages/Login/LoginForm.tsx
  vite.config.ts
Labels: 🎨 design, 🐾 feature

#6 팀 참여 화면 퍼블리싱
  src/assets/.gitkeep
  src/assets/TeamDashboard/arrow.png
  src/assets/TeamDashboard/click.png
  src/components/.gitkeep
  src/components/commons/Box.tsx
  src/components/commons/Button.tsx
  src/components/commons/FilterButtons.tsx
  src/components/commons/Pagination.tsx
  src/components/features/TeamDashboard/MyTeamCard.tsx
  src/components/features/TeamDashboard/ProfileList.tsx
  src/components/features/TeamDashboard/TeamList.tsx
  src/constants/.gitkeep
  src/constants/colors.ts
  src/pages/.gitkeep
  src/pages/TeamDashboard/TeamDashboard.tsx
  src/routes/path.ts
  src/routes/router.tsx
Labels: 🎨 design, 🐾 feature

#7 그라데이션 배경 컴포넌트 리팩터링
  src/components/commons/BackgroundGradient.tsx
  src/components/features/TeamDashboard/MyTeamCard.tsx
  src/components/features/TeamDashboard/TeamList.tsx
  src/pages/Login/Login.tsx
Labels: 🎨 design, 🛠️ refactor

#9 캘린더 퍼블리싱
  package-lock.json
  package.json
  src/assets/TeamCalendar/mark.png
  src/components/Layout/MultiSectionHeader.tsx
  src/components/commons/Button.tsx
  src/components/commons/Calendar/Calendar.tsx
  src/components/commons/ComonFormTitle.tsx
  src/components/commons/GlassCard.tsx
  src/components/commons/Header.tsx
  src/components/commons/PageSectionHeader.tsx
  src/components/commons/Pagination.tsx
  src/components/features/TeamDashboard/MyTeamCard.tsx
  src/components/features/TeamDashboard/TeamList.tsx
  src/main.css
  src/pages/TeamCalendar/TeamCalendar.tsx
  src/pages/TeamDashboard/TeamDashboard.tsx
  src/routes/path.tsx
  src/routes/router.tsx
  src/templates/Enroll/ProfileSubmitButton.tsx
  src/templates/Login/LoginForm.tsx
Labels: 🎨 design
