Repository PNUMeat/comon-fe, pull requests merged in 2024-12, with the labels that each got.

#12 랜딩 페이지 디자인 픽스된 곳까지 구현
  src/assets/Home/comonBanner.png
  src/assets/Home/goalAchievement.svg
  src/assets/Home/goalContinually.svg
  src/assets/Home/goalTogether.svg
  src/components/commons/Header.tsx
  src/components/commons/LazyImage.tsx
  src/pages/Home/Home.tsx
Labels: 🎨 design

#14 Suspense에 fallback이 너무 빨리 걷어지면, 화면이 깜빡거리는 거처럼 보여서 fallback 최소 화면 유지 시간 추가
  eslint.config.js
  src/components/commons/Form/ComonTextarea.tsx
  src/components/layout/SingleSectionLayout.tsx
  src/routes/Lazies.tsx
  src/routes/path.tsx
  src/routes/pathTitles.tsx
  src/routes/router.tsx
  src/templates/Team/TeamFormLayout.tsx
  src/templates/User/ModificationSubmitButton.tsx
Labels: 🐾 feature

#15 Box 컴포넌트 리팩터링
  src/components/commons/Box.tsx
  src/components/commons/Label.tsx
  src/components/features/TeamDashboard/MyTeamCard.tsx
  src/components/features/TeamDashboard/TeamList.tsx
  src/pages/TeamDashboard/TeamDashboard.tsx
Labels: 🛠️ refactor

#18 나의 팀 및 전체 팀 조회 API 연결
  .github/workflows/cicd.yml
  src/api/team/createTeam.ts
  src/api/team/getTeamList.ts
  src/components/features/TeamDashboard/MyTeamCard.tsx
  src/components/features/TeamDashboard/ProfileList.tsx
  src/components/features/TeamDashboard/TeamList.tsx
  src/pages/TeamDashboard/TeamDashboard.tsx
  src/templates/Team/TeamRegistrationButton.tsx
Labels: 🎨 design, 🛠️ refactor, 🐾 feature

#19 팀 조회 화면 디자인 수정, 팀 관련 API 요청 함수 하나의 파일에 통합, 페이지네이션 적용
  src/api/team.ts
  src/api/team/createTeam.ts
  src/api/team/getTeamList.ts
  src/components/commons/Pagination.tsx
  src/components/features/TeamDashboard/MyTeamCard.tsx
  src/components/features/TeamDashboard/TeamList.tsx
  src/pages/TeamDashboard/TeamDashboard.tsx
  src/templates/Team/TeamRegistrationButton.tsx
Labels: 🎨 design, 🛠️ refactor

#20 flip card 구현 및 팀 참가 API 연결
  src/api/team.ts
  src/api/types.ts
  src/components/features/TeamDashboard/TeamList.tsx
Labels: 🛠️ refactor, 🐾 feature

#24 TeamDashboard 화면 디자인 수정 및 리팩터링
  src/components/commons/Box.tsx
  src/components/commons/Button.tsx
  src/components/commons/Calendar/Calendar.tsx
  src/components/commons/Pagination.tsx
  src/components/features/TeamDashboard/CalendarAndPosts.tsx
  src/components/features/TeamDashboard/SidebarAndAnnouncement.tsx
  src/pages/TeamDashboard/TeamDashboard.tsx
Labels: 🎨 design, 🛠️ refactor

#28 팀 정보 및 캘린더 태그 조회 API 연결
  src/api/dashboard.ts
  src/api/team.ts
  src/components/commons/Calendar/Calendar.tsx
  src/components/commons/Tag.tsx
  src/components/features/TeamDashboard/CalendarAndPosts.tsx
  src/components/features/TeamDashboard/Posts.tsx
  src/components/features/TeamDashboard/SidebarAndAnnouncement.tsx
  src/components/features/TeamJoin/MyTeamCard.tsx
  src/components/layout/SingleSectionLayout.tsx
  src/pages/TeamDashboard/TeamDashboard.tsx
  src/routes/pathTitles.tsx
  src/routes/router.tsx
Labels: 🎨 design, 🛠️ refactor, 🐾 feature

#30 메인페이지 디자인 관련 수정
  src/components/commons/Container.tsx
  src/components/commons/Flex.tsx
  src/components/commons/SText.tsx
  src/components/commons/Spacer.tsx
  src/components/features/Post/editor.css
  src/components/features/Post/plugins/ToolbarPlugin.tsx
  src/components/features/Post/segments/FontDropdown.tsx
  src/components/layout/CommonLayout.tsx
  src/pages/Home/Home.tsx
  src/pages/TeamAdmin/TeamAdmin.tsx
Labels: 🎨 design, 🐾 feature

#31 TeamDashboard 화면 API 연결
  src/api/dashboard.ts
  src/components/commons/Box.tsx
  src/components/commons/Calendar/Calendar.tsx
  src/components/commons/LazyImage.tsx
  src/components/features/TeamDashboard/ArticleDetail.tsx
  src/components/features/TeamDashboard/Posts.tsx
  src/components/features/TeamDashboard/SidebarAndAnnouncement.tsx
  src/components/features/TeamDashboard/TopicDetail.tsx
  src/components/features/TeamJoin/MyTeamCard.tsx
  src/pages/TeamDashboard/TeamDashboard.tsx
Labels: 🎨 design, 🛠️ refactor, 🐾 feature

#32 TeamDashboard 화면 디자인 수정 및 무한 로딩 버그 해결
  src/components/commons/LazyImage.tsx
  src/components/features/TeamDashboard/ArticleDetail.tsx
  src/components/features/TeamDashboard/Posts.tsx
  src/components/features/TeamDashboard/TopicDetail.tsx
  src/pages/TeamDashboard/TeamDashboard.tsx
  src/routes/router.tsx
Labels: 🐞 bug, 🎨 design

#33 feat: 메인페이지 배경변경
  src/pages/Home/Home.tsx
Labels: 🎨 design

#34 나의 팀 리스트 슬라이더 뷰 적용
  src/components/features/TeamJoin/MyTeamCard.tsx
  src/pages/TeamAdmin/TeamAdmin.tsx
Labels: 🎨 design

#37 TeamDashboard 관리자 화면 구현
  src/api/announcement.ts
  src/api/dashboard.ts
  src/assets/TeamDashboard/deleteIcon.png
  src/assets/TeamDashboard/modifyIcon.png
  src/components/features/TeamDashboard/ArticleDetail.tsx
  src/components/features/TeamDashboard/SidebarAndAnnouncement.tsx
  src/pages/TeamAdmin/TeamAdmin.tsx
  src/routes/pathTitles.tsx
Labels: 🎨 design, 🐾 feature

#52 대시보드 페이지 깜빡임 제거 및 게시글 이미지 삭제 추가
  src/components/features/Post/nodes/ImageNode.tsx
  src/components/features/Post/nodes/LazyEditorImage.tsx
  src/pages/TeamDashboard/TeamDashboard.tsx
  src/routes/Lazies.tsx
Labels: 🎨 design, 🐾 feature

#53 404 페이지 추가
  src/assets/NotFound/404.png
  src/pages/NotFound/NotFound.tsx
  src/routes/router.tsx
Labels: 🎨 design, 🐾 feature

#54 피드백 반영
  src/api/team.ts
  src/assets/TeamJoin/search.png
  src/components/commons/Calendar/Calendar.tsx
  src/components/commons/Header.tsx
  src/components/features/TeamJoin/MyTeamCard.tsx
  src/components/features/TeamJoin/SearchBar.tsx
  src/components/features/TeamJoin/TeamList.tsx
  src/pages/TeamAdmin/TeamAdmin.tsx
  src/pages/TeamDashboard/TeamDashboard.tsx
  src/pages/TeamJoin/TeamJoin.tsx
Labels: 🎨 design, 🛠️ refactor, 🐾 feature

#55 헤더 모달 추가
  src/components/commons/Header.tsx
  src/components/layout/CommonLayout.tsx
Labels: 🐾 feature

#56 팀 검색 기능 연결
  src/api/team.ts
  src/components/features/TeamJoin/SearchBar.tsx
  src/components/features/TeamJoin/TeamList.tsx
  src/pages/TeamJoin/TeamJoin.tsx
Labels: 🐾 feature

#57 게시글 수정 추가
  src/api/postings.ts
  src/components/features/TeamDashboard/ArticleDetail.tsx
  src/pages/Posting/Posting.tsx
  src/pages/TeamAdmin/TeamAdmin.tsx
  src/pages/TeamDashboard/TeamDashboard.tsx
Labels: 🐾 feature

#58 location state 필드 명 수정
  src/pages/Posting/Posting.tsx
Labels: 🐞 bug

#59 게시글 및 주제 수정 추가
  src/api/subject.ts
  src/components/features/TeamDashboard/ArticleDetail.tsx
  src/components/features/TeamDashboard/TopicDetail.tsx
  src/pages/Posting/Posting.tsx
  src/pages/Posting/TeamDailySubject.tsx
  src/pages/TeamAdmin/TeamAdmin.tsx
  src/store/posting.ts
  src/store/subject.ts
Labels: 🐾 feature

#60 Carousel 화살표 버튼 동작 구현
  src/assets/TeamJoin/carousel_arrow.png
  src/assets/TeamJoin/pagination_arrow.png
  src/components/commons/Pagination.tsx
  src/components/features/TeamJoin/MyTeamCard.tsx
  src/components/features/TeamJoin/TeamList.tsx
  src/templates/User/EnrollForm.tsx
Labels: 🎨 design, 🐾 feature

#61 게시글 및 주제 수정시 기본 값으로 채워지도록 변경
  src/components/features/Post/PostEditor.tsx
  src/components/features/Post/plugins/ToolbarPlugin.tsx
  src/pages/Posting/Posting.tsx
  src/pages/Posting/TeamDailySubject.tsx
Labels: 🐾 feature

#62 게시글 링크 라우팅 수정
  src/components/features/TeamDashboard/TopicDetail.tsx
Labels: 🐞 bug

#63 게시글 수정 요청 url 수정
  src/api/postings.ts
Labels: 🐞 bug

#64 팀리스트 캐러셀 사이즈 변경
  src/components/features/TeamJoin/MyTeamCard.tsx
Labels: 🎨 design

#65 구글 태그 매니저 스크립트 추가
  index.html
  src/components/commons/Header.tsx
  src/components/features/TeamDashboard/ArticleDetail.tsx
  src/components/layout/CommonLayout.tsx
  src/pages/TeamAdmin/TeamAdmin.tsx
Labels: 🎨 design, 🐾 feature

#66 팀장 페이지에서 아티클 조회시 빈 이미지 제거
  src/components/features/TeamDashboard/ArticleDetail.tsx
Labels: 🐾 feature

#67 ArticleDetail 아티클이 선택 되지 않았을 때, 이미지 태그 제거
  src/components/features/TeamDashboard/ArticleDetail.tsx
  src/templates/Team/TeamRegistrationButton.tsx
Labels: 🐾 feature

#68 기존 Carousel react-slick으로 변경, 캘린더에 activeStartDate 상태 추가
  package-lock.json
  package.json
  src/components/commons/Calendar/Calendar.tsx
  src/components/features/TeamJoin/MyTeamCard.tsx
Labels: 🐞 bug, 🛠️ refactor

#69 디자인 변경사항 반영
  src/assets/TeamDashboard/announcement_purple.png
  src/assets/TeamDashboard/rocket.png
  src/components/commons/Tag.tsx
  src/components/features/Post/PostEditor.tsx
  src/components/features/Post/plugins/ToolbarPlugin.tsx
  src/components/features/Post/segments/FontDropdown.tsx
  src/components/features/TeamDashboard/Posts.tsx
  src/components/features/TeamDashboard/SidebarAndAnnouncement.tsx
  src/pages/Posting/TeamDailySubject.tsx
  src/pages/TeamAdmin/TeamAdmin.tsx
Labels: 🎨 design
