Repository PNUMeat/comon-fe, pull requests merged in 2025-01, with the labels that each got.

#70 CommonLayout.tsx 수정
  src/components/layout/CommonLayout.tsx
Labels: 🐞 bug, 🛠️ refactor

#71 기능 변경 요청 반영
  src/api/apiInstance.ts
  src/components/commons/Pagination.tsx
  src/pages/TeamDashboard/TeamDashboard.tsx
Labels: 🎨 design, 🐾 feature

#72 auth 핸들링 로그 출력
  src/api/apiInstance.ts
  src/pages/TeamDashboard/TeamDashboard.tsx
Labels: 🐾 feature

#74 이벤트 플로팅 버튼 수정
  src/assets/EventFloating/BubbleIcon.svg
  src/assets/EventFloating/ButtonIcon.svg
  src/assets/EventFloating/gift.png
  src/assets/EventFloating/speech_bubble.png
  src/components/commons/EventFloating/EventFloating.tsx
  src/components/commons/EventFloating/EventFloatingButton.tsx
  src/components/commons/EventFloating/EventFloatingContent.tsx
Labels: 🎨 design

#75 스페이싱 수정
  src/components/commons/Form/ComonImageInput.tsx
  src/components/commons/Form/segments/FormFieldLabel.tsx
  src/components/features/TeamDashboard/SidebarAndAnnouncement.tsx
  src/components/features/TeamJoin/MyTeamCard.tsx
  src/components/features/TeamJoin/TeamList.tsx
  src/pages/Home/Home.tsx
  src/pages/TeamJoin/TeamJoin.tsx
  src/templates/Login/LoginForm.tsx
  src/templates/Team/TeamFormLayout.tsx
Labels: 🎨 design

#76 게시글 작성 마크 다운 단축키 추가
  src/components/features/Post/PostEditor.tsx
  src/components/features/Post/plugins/InitContentPlugin.tsx
  src/components/features/Post/plugins/markdownShortcuts.ts
  src/components/features/TeamDashboard/ArticleDetail.tsx
  src/components/features/TeamDashboard/TopicDetail.tsx
  src/templates/MyDashboard/MyTeams.tsx
  src/utils/viewStyle.ts
Labels: 🐾 feature

#78 게시글 링크, 코드블럭 단축키 추가
  package-lock.json
  package.json
  src/components/features/Post/PostEditor.tsx
  src/components/features/Post/plugins/CodeActionPlugin.tsx
  src/components/features/Post/plugins/HighlightCodePlugin.ts
  src/components/features/Post/plugins/markdownShortcuts.ts
  src/components/features/Post/utils.ts
  src/routes/router.tsx
  src/utils/viewStyle.ts
Labels: 🐾 feature

#80 코드블럭 HTML로 변환하는 로직 수정
  src/components/features/Post/PostEditor.tsx
Labels: 🐾 feature

#81 게시글 이미지 업로드 방법 추가
  src/components/features/Post/PostEditor.tsx
Labels: 🐾 feature

#84 Mingkyeongg
  index.html
  src/components/commons/Modal/Alert.tsx
  src/components/commons/Modal/Confirm.tsx
  src/components/commons/Modal/Modal.tsx
  src/components/features/TeamDashboard/ArticleDetail.tsx
  src/components/layout/CommonLayout.tsx
  src/pages/Posting/Posting.tsx
  src/store/modal.ts
  src/templates/Team/TeamRegistrationButton.tsx
  src/templates/User/EnrollSubmitButton.tsx
Labels: 🐾 feature

#85 fix: 승인 눌러도 안꺼지는 문제 해결
  src/components/commons/Modal/Confirm.tsx
Labels: 🐞 bug

#86 게시글 작성기 드래그앤드롭으로 노드 이동시키는 기능 추가
  src/components/features/Post/PostEditor.tsx
  src/components/features/Post/editor.css
  src/components/features/Post/plugins/DraggablePlugin.tsx
  src/components/features/TeamDashboard/TopicDetail.tsx
  src/pages/Posting/TeamDailySubject.tsx
  src/pages/TeamAdmin/TeamAdmin.tsx
Labels: 🐞 bug, 🐾 feature

#87 요소 이동 드래그앤드롭 사용감 개선
  src/components/features/Post/PostEditor.tsx
  src/components/features/Post/editor.css
Labels: 🐾 feature

#88 드래그앤드롭 맨위로 안보내 지던 부분 수정
  src/components/features/Post/plugins/DraggablePlugin.tsx
Labels: 🐞 bug

#89 팀 주제 작성 및 수정 버튼 주제 불러오는 쿼리 추가
  src/pages/TeamAdmin/TeamAdmin.tsx
Labels: 🐾 feature

#90 팀 주제 캘린더 지난달 없어지던 부분 수정
  src/pages/TeamAdmin/TeamAdmin.tsx
  src/pages/TeamDashboard/TeamDashboard.tsx
Labels: 🐞 bug

#91 모바일 헤더 구현
  src/assets/Header/logo_eng.png
  src/assets/Header/logo_ko.png
  src/components/commons/Container.tsx
  src/components/commons/Header.tsx
  src/components/layout/CommonLayout.tsx
  src/constants/breakpoints.ts
Labels: 🎨 design

#94 Container 모바일 디폴트 padding 값 변경
  src/components/commons/BackgroundGradient.tsx
  src/components/commons/Container.tsx
  src/pages/Home/Home.tsx
  src/templates/Login/LoginForm.tsx
Labels: 🎨 design

#95 활동 팀 찾기 모바일 화면 퍼블리싱
  src/components/commons/Button.tsx
  src/components/commons/Container.tsx
  src/components/commons/Header.tsx
  src/components/commons/PageSectionHeader.tsx
  src/components/commons/Pagination.tsx
  src/components/commons/Title.tsx
  src/components/features/TeamJoin/SearchBar.tsx
  src/components/features/TeamJoin/TeamList.tsx
  src/pages/Home/Home.tsx
  src/pages/TeamJoin/TeamJoin.tsx
  src/routes/pathTitles.tsx
  src/templates/Login/LoginForm.tsx
  src/templates/MyDashboard/Profile.tsx
Labels: 🎨 design

#96 게시글 이미지 src가 blobk일 때만 ?로 변환
  src/components/features/Post/PostEditor.tsx
  src/pages/Posting/Posting.tsx
  src/pages/Posting/TeamDailySubject.tsx
Labels: 🐾 feature

#97 폰트 수정
  src/components/commons/EventFloating/EventFloatingContent.tsx
  src/components/features/TeamJoin/MyTeamCard.tsx
Labels: 🐞 bug

#98 위도우에서 화면 크기 breakpoint mobile 보다 작으면 스크롤바 숨김처리
  src/components/commons/Container.tsx
  src/components/layout/CommonLayout.tsx
  src/pages/Home/Home.tsx
Labels: 🐾 feature

#99 화면 헤더 아래에서 고정되던 부분 수정
  src/components/layout/CommonLayout.tsx
Labels: 🐞 bug, 🐾 feature

#100 모바일뷰 스크롤 안보이도록 추가
  .github/workflows/develop-to-main-batch.yml
  src/pages/Home/Home.tsx
Labels: 🐾 feature

#101 Develop
  .github/workflows/develop-to-main-batch.yml
  src/pages/Home/Home.tsx
Labels: 🕸️ merge

#103 나의 팀 모바일 화면 구현
  src/components/commons/Box.tsx
  src/components/commons/Label.tsx
  src/components/features/TeamJoin/MyTeamCard.tsx
Labels: 🎨 design

#104 스크롤 복구
  src/components/commons/Container.tsx
  src/components/layout/CommonLayout.tsx
  src/pages/Home/Home.tsx
Labels: 🎨 design
